name: redis-poc
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  mongodb:
    extends:
      file: mongo-db.yml
      service: mongodb
  app:
    image: cache-poc-app
    ports:
      - 127.0.0.1:8080:8080
    restart: on-failure
    depends_on:
      mongodb:
        condition: service_healthy
